# https://goreleaser.com
version: 2
project_name: autoscan

# Build
builds:
  - id: autoscan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    main: ./cmd/autoscan
    binary: autoscan
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w
      - -X "main.Version={{ .Version }}"
      - -X "main.GitCommit={{ .ShortCommit }}"
      - -X "main.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

# MacOS Universal Binaries
universal_binaries:
  -
    replace: true

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

# Checksum
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

# Snapshot
snapshot:
  version_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .Branch  }}"

# Changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999